name: mygitprompt test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install deps
      run: sudo apt install -y meson make
    - name: init
      run: meson setup builddir -Doptimization=3 -Dwarning_level=3
    - name: test
      run: meson test -C builddir/ -v
